repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  -  id: trailing-whitespace
  -  id: end-of-file-fixer
  -  id: check-added-large-files
  -  id: pretty-format-json
  -  id: name-tests-test
  -  id: detect-private-key

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  -  id: python-no-log-warn
  -  id: python-check-mock-methods

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    args: ['--config=xpd_api/setup.cfg']
    additional_dependencies:
    - flake8-no-pep420==2.0.0
    - flake8-breakpoint==1.1.0
